server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 86930438633-5a00mf173sfcv458favnqelj8irlac4h.apps.googleusercontent.com
            client-secret: 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

  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/compahunt
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: false

  flyway:
    enabled: false


  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_

app:
  encryption:
                        #    In HEX!!!
    key: 56d04a517a1fa6629f12cb0529a1b56fc203ff2af2f710639dfcb016f61d5362
  jwt:
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxrmCLw7mvxqWqkfMVDw4
      vbvatvFbPYAwnSdeDyxumEiHZ0q+ZG2uAjZ2hAvbrsMhwpc95Njq+GcKhHuQxDYc
      crYa5S1knAxGVuAAejt0kwk+npq2fg0/YuNclnX4rFSz6kc7zGE8N8tiTC6c2dtV
      psI9TEwRaSZuY9GhGaDNa8dO2qa/7CGcxrxeLY+REVQ+EorUWp+kdaHqT4MECnOf
      iuRxduT5Qw3tjtdL1vHVHLGmZMvbZfzvuMGSW2g0l+cTrRpcc/LjiA0pRlCHIXLe
      4ks1rFch8gB3XHPx2Hdtk/8R7KBwlD0dLDlodR8ND1Jmi8zg0iFufu2bzibiIKI0
      /QIDAQAB
      -----END PUBLIC KEY-----